Controllers/AddressBooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Address_Book.Data;
using Address_Book.Models;

namespace Address_Book.Controllers
{
    public class AddressBooksController : Controller
    {
        private DBContext db = new DBContext();

        // GET: AddressBook
        public async Task<ActionResult> Index()
        {
            return View(await db.Address_Book.ToListAsync());
        }

        // GET: AddressBook/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AddressBook address_Book = await db.Address_Book.FindAsync(id);
            if (address_Book == null)
            {
                return HttpNotFound();
            }
            return View(address_Book);
        }

        // GET: AddressBook/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AddressBook/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AddressBook address_Book)
        {
            if (ModelState.IsValid)
            {
                if (Request.Files.Count > 0)
                    if (Request.Files["file"] != null)
                        if (Request.Files["file"].ContentLength > 0)
                {
                    if (!System.IO.Directory.Exists(Server.MapPath("~/Uploads")))
                        System.IO.Directory.CreateDirectory(Server.MapPath("~/Uploads"));

                    if (!System.IO.Directory.Exists(Server.MapPath("~/Uploads/Contacts")))
                        System.IO.Directory.CreateDirectory(Server.MapPath("~/Uploads/Contacts"));

                    address_Book.FileType = Request.Files[0].ContentType;
                    string ImageName = $"~/Uploads/Contacts/{Guid.NewGuid().ToString()}" +
                        Request.Files[0].FileName.Substring(Request.Files[0].FileName.LastIndexOf("."));
                    address_Book.FileName = Request.Files[0].FileName;
                    address_Book.FilePath = ImageName;
                    Request.Files[0].SaveAs(Server.MapPath(ImageName));
                }
                address_Book.CreationDate = DateTime.Now;

                db.Address_Book.Add(address_Book);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(address_Book);
        }

        // GET: AddressBook/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AddressBook address_Book = await db.Address_Book.FindAsync(id);
            if (address_Book == null)
            {
                return HttpNotFound();
            }
            return View(address_Book);
        }

        // POST: AddressBook/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(AddressBook address_Book)
        {
            if (ModelState.IsValid)
            {
                AddressBook addressBook = db.Address_Book.Find(address_Book.Id);

                if (Request.Files.Count > 0)
                    if (Request.Files["file"] != null)
                        if (Request.Files["file"].ContentLength > 0)
                {
                    if (!System.IO.Directory.Exists(Server.MapPath("~/Uploads")))
                        System.IO.Directory.CreateDirectory(Server.MapPath("~/Uploads"));

                    if (!System.IO.Directory.Exists(Server.MapPath("~/Uploads/Contacts")))
                        System.IO.Directory.CreateDirectory(Server.MapPath("~/Uploads/Contacts"));


                    if (!string.IsNullOrEmpty(addressBook.FilePath))
                    {
                        if (System.IO.File.Exists(Server.MapPath(addressBook.FilePath)))
                            System.IO.File.Delete(Server.MapPath(addressBook.FilePath));
                    }

                    addressBook.FileType = Request.Files[0].ContentType;
                    string ImageName = $"~/Uploads/Contacts/{Guid.NewGuid().ToString()}" +
                        Request.Files[0].FileName.Substring(Request.Files[0].FileName.LastIndexOf("."));
                    addressBook.FileName = Request.Files[0].FileName;
                    addressBook.FilePath = ImageName;
                    Request.Files[0].SaveAs(Server.MapPath(ImageName));
                }

                addressBook.OfficeNumber = address_Book.OfficeNumber;
                addressBook.Name = address_Book.Name;
                addressBook.MobileNumber = address_Book.MobileNumber;
                addressBook.Email = address_Book.Email;
                addressBook.Hometown = address_Book.Hometown;

                db.Entry(addressBook).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(address_Book);
        }

        // GET: AddressBook/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AddressBook address_Book = await db.Address_Book.FindAsync(id);
            if (address_Book == null)
            {
                return HttpNotFound();
            }
            return View(address_Book);
        }

        // POST: AddressBook/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            AddressBook address_Book = await db.Address_Book.FindAsync(id);


            if (!string.IsNullOrEmpty(address_Book.FilePath))
            {
                if (System.IO.File.Exists(Server.MapPath(address_Book.FilePath)))
                    System.IO.File.Delete(Server.MapPath(address_Book.FilePath));
            }


            db.Address_Book.Remove(address_Book);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Address Book</title>
    @using System.Web.Optimization
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            @Html.ActionLink("Address Book", "Index", "Home", 
               new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        @Html.ActionLink("Home", "Index", "Home", null,
                            new { @class = "nav-link active" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Address Books", "Index", "AddressBooks", null,
                            new { @class = "nav-link" })
                    </li>
                    <li class="nav-item dropdown" hidden>
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Dropdown
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                </ul>
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Address Book</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/js")
    @RenderSection("scripts", required: false)
</body>
</html>